vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
      bureau_images:
        uri_prefix: /images
        upload_destination: '%kernel.project_dir%/public/images'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
